[Interface]
Address = 10.10.10.10/24
ListenPort = 7000
PrivateKey = yPjffkEFH3SAerBEgKuM1mnp7I2Y5TEb2Y9aKzTmwWU=


[Peer]
PublicKey = PI1mie11niZ+XrprIkYQSKFlMKPasB6J6DsY6UX8ngw=
AllowedIPs = 10.10.10.1/32
Endpoint = 192.168.100.1:8000
