[Interface]
PrivateKey = yPjffkEFH3SAerBEgKuM1mnp7I2Y5TEb2Y9aKzTmwWU=
ListenPort = 7000

[Peer]
# Server (test host) public key, derived from server_private_key in target.py
PublicKey = PI1mie11niZ+XrprIkYQSKFlMKPasB6J6DsY6UX8ngw=
AllowedIPs = 10.10.10.1/32
Endpoint = 192.168.100.1:8000
