[Interface]
Address = 10.10.10.1/24
ListenPort = 8000
PrivateKey = sOrI0RWLJAVbczm0jOrPSMTzJ8tGGbPNXrCesFeGtkI=

[Peer]
PublicKey = T6RSDuZEb5VY0q7BWbK0wgF9ltThMpcLesoWOfkQ4Xk=
AllowedIPs = 10.10.10.10/32
